package models

// 都道府県
type Prefecture string

const (
	Online    Prefecture = "online"
	Hokkaido  Prefecture = "hokkaido"
	Aomori    Prefecture = "aomori"
	Iwate     Prefecture = "iwate"
	Miyagi    Prefecture = "miyagi"
	Akita     Prefecture = "akita"
	Yamagata  Prefecture = "yamagata"
	Fukushima Prefecture = "fukushima"
	Ibaraki   Prefecture = "ibaraki"
	Tochigi   Prefecture = "tochigi"
	Gunma     Prefecture = "gunma"
	Saitama   Prefecture = "saitama"
	Chiba     Prefecture = "chiba"
	Tokyo     Prefecture = "tokyo"
	Kanagawa  Prefecture = "kanagawa"
	Yamanashi Prefecture = "yamanashi"
	Nagano    Prefecture = "nagano"
	Niigata   Prefecture = "niigata"
	Toyama    Prefecture = "toyama"
	Ishikawa  Prefecture = "ishikawa"
	Fukui     Prefecture = "fukui"
	Gifu      Prefecture = "gifu"
	Shizuoka  Prefecture = "shizuoka"
	Aichi     Prefecture = "aichi"
	Mie       Prefecture = "mie"
	Shiga     Prefecture = "shiga"
	Kyoto     Prefecture = "kyoto"
	Osaka     Prefecture = "osaka"
	Hyogo     Prefecture = "hyogo"
	Nara      Prefecture = "nara"
	Wakayama  Prefecture = "wakayama"
	Tottori   Prefecture = "tottori"
	Shimane   Prefecture = "shimane"
	Okayama   Prefecture = "okayama"
	Hiroshima Prefecture = "hiroshima"
	Yamaguchi Prefecture = "yamaguchi"
	Tokushima Prefecture = "tokushima"
	Kagawa    Prefecture = "kagawa"
	Ehime     Prefecture = "ehime"
	Kochi     Prefecture = "kochi"
	Fukuoka   Prefecture = "fukuoka"
	Saga      Prefecture = "saga"
	Nagasaki  Prefecture = "nagasaki"
	Kumamoto  Prefecture = "kumamoto"
	Oita      Prefecture = "oita"
	Miyazaki  Prefecture = "miyazaki"
	Kagoshima Prefecture = "kagoshima"
	Okinawa   Prefecture = "okinawa"
)
